[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'runtime/common',
  'runtime/basilisk',
  'runtime/testing-basilisk',
  'pallets/nft',
  'pallets/duster',
  'pallets/xyk',
  'pallets/exchange',
  'pallets/asset-registry',
  'pallets/liquidity-mining',
  'integration-tests',
]
