[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'runtime',
  'pallets/nft',
  'pallets/duster',
  'pallets/xyk',
  'pallets/exchange',
  'pallets/asset-registry',
  'integration-tests',
]
