[patch.crates-io]
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
frame-benchmarking-cli = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
frame-executive = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
frame-support = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
frame-system-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-authorship = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-aura = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-collective = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-democracy = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-session = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-scheduler = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-sudo = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-tips = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-treasury= { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-transaction-payment-rpc = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-basic-authorship = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-cli = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-client-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-client-db = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-consensus = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-consensus-epochs = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-executor = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-informant = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-keystore = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-network = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-offchain = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-rpc = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-rpc-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-service = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-telemetry = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sc-tracing = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-api = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-application-crypto = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-arithmetic = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-blockchain = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-consensus = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-externalities = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-finality-grandpa = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-inherents = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-offchain = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-rpc = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-runtime-interface = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-session = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-std = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-staking = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-storage = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-state-machine = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-timestamp = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-tracing = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-trie = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
sp-version = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
substrate-frame-rpc-system = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
substrate-test-client = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
substrate-test-runtime-client = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-elections-phragmen = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }
pallet-utility = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.8" }

sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }

pallet-collator-selection = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8" }


# ORML dependencies
orml-xcm-support = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }
orml-xtokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }
orml-unknown-tokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }

xcm = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }
pallet-xcm = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }
xcm-builder = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }
xcm-executor = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }

cumulus-pallet-xcm = { git = 'https://github.com/paritytech/cumulus',  default-features = false, branch = "polkadot-v0.9.8" }
cumulus-pallet-xcmp-queue = { git = 'https://github.com/paritytech/cumulus',  default-features = false, branch = "polkadot-v0.9.8" }
cumulus-pallet-dmp-queue = { git = 'https://github.com/paritytech/cumulus',  default-features = false, branch = "polkadot-v0.9.8" }

orml-currencies = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }
orml-tokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }
orml-traits = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }
orml-utilities = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }
orml-vesting = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = 'ca054d3078a8d157d0c176ed319d6ff49f38d349' }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
polkadot-test-service = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.8" }
polkadot-runtime-common = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }
polkadot-test-runtime = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }
polkadot-test-client = { git = 'https://github.com/paritytech/polkadot', branch = "release-v0.9.8" }
# Cumulus
cumulus-client-cli = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8"}
cumulus-client-collator = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8"}
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8" }
cumulus-client-consensus-relay-chain = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8"}
cumulus-client-consensus-common = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8" }
cumulus-client-network = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8"}
cumulus-client-service = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8"}
cumulus-primitives-core = {git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8"}
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.8" }

cumulus-pallet-aura-ext = { git = 'https://github.com/paritytech/cumulus',  default-features = false, branch = "polkadot-v0.9.8" }
cumulus-pallet-parachain-system = { git = 'https://github.com/paritytech/cumulus',  default-features = false, branch = "polkadot-v0.9.8" }
parachain-info = { git = 'https://github.com/paritytech/cumulus',  default-features = false, branch = "polkadot-v0.9.8" }

# HydraDX utils
hydra-dx-build-script-utils = { git = "https://github.com/galacticcouncil/HydraDX-node", branch = "master" }

[profile.release]
panic = 'unwind'

[workspace]
members = [
  # 'pallets/proposal', Update this
  'node',
  'pallets/nft',
  'runtime',
  'pallets/xyk',
  'pallets/exchange',
]
