[package]
authors = ['GalacticCouncil']
description = 'Transaction Payment Benchmarking Module'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/basilisk-node'
license = 'Apache 2.0'
name = 'pallet-multi-payment-benchmarking'
repository = 'https://github.com/galacticcouncil/basilisk-node'
version = '4.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = '4.0.0'

# alias "parity-scale-code" to "codec"
[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
serde = {features = ['derive'], optional = true, version = '1.0.101'}

# Local dependencies
pallet-xyk = {path = '../../xyk', default-features = false}
pallet-registry = {path = '../../registry', default-features = false}
pallet-transaction-multi-payment = {path = '../../transaction-multi-payment', default-features = false}
primitives = {path = '../../../primitives', default-features = false}

# ORML dependencies
orml-currencies = {default-features = false, version = "0.4.1-dev"}
orml-tokens = {default-features = false, version = "0.4.1-dev"}
orml-traits = {default-features = false, version = "0.4.1-dev"}
orml-utilities = {default-features = false, version = "0.4.1-dev"}

# Substrate dependencies
frame-benchmarking = {default-features = false, version = '3.0.0'}
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
frame-system-benchmarking = {default-features = false, version = '3.0.0'}

pallet-balances = {default-features = false, version = "3.0.0"}
pallet-transaction-payment = {default-features = false, version = '3.0.0'}

sp-std = {default-features = false, version = '3.0.0'}
sp-core = {default-features = false, version = '3.0.0'}
sp-runtime = {default-features = false, version = '3.0.0'}

[dev-dependencies]
sp-io = {default-features = false, version = '3.0.0'}

[features]
default = ['std']
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-std/std',
  'sp-runtime/std',
  'primitives/std',
  'pallet-xyk/std',
  'pallet-registry/std',
  'pallet-transaction-multi-payment/std',
  "frame-benchmarking/std",
]
